package com.lion.buyershop.util

enum class MainScreenName{
    //MAIN_SCREEN_BUYER_MAIN,
    //MAIN_SCREEN_BUYER_FIRST,
    MAIN_SCREEN_BUY_LIST,
    MAIN_SCREEN_PRODUCT_INFO,
    MAIN_SCREEN_ORDER,
    MAIN_SCREEN_MAIN,
    MAIN_SCREEN_MY_PAGE,
    MAIN_SCREEN_USER_LOGIN,
    MAIN_SCREEN_USER_JOIN_STEP1,
    MAIN_SCREEN_USER_JOIN_STEP2,





}